name: Test GHA

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/gha.yml
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test Action?
        uses: nhendri/test-docker-action@main
        with:
          ENV_VAR01: "holy"
          ENV_VAR02: "wah"
