name: Get Some Info Workflow

on:
  push:
    branches:
      - main
    paths:
    - .github/workflows/tmp.yml
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Script
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
          AWS_DEFAULT_REGION: ${{ vars.aws_region }}
          TF_VAR_public_key: ${{ secrets.mba_puk }}
        run: |
            echo "::set-output name=context::${GITHUB_EVENT_PATH}"
            cat $GITHUB_EVENT_PATH
